### PR TITLE
update the website with new logo and add a blog entry

### PR DESCRIPTION
**Pull request by ywang-gilead**

### CODE REVIEW

**Comment by danielinteractive** [comment]
Looks good, thanks @ywang-gilead ! Only idea I would have is whether @ellessenne could help to align the colors of the website? :-)

**Comment by danielinteractive** [comment]
ok let's first merge this one

**Review by danielinteractive — APPROVED** [review]

**Comment by ellessenne** [comment]
Hi @danielinteractive and @ywang-gilead – I have been away for a couple of weeks but I am now back, will start working on a separate PR for the website theme :)

**Comment by danielinteractive** [comment]
awesome, thanks @ellessenne and welcome back :) hope you had great vacations

**Pull request merged**
