### PR TITLE
Hex Sticker 

### PR DESCRIPTION
**Pull request by ellessenne**
Hi,
This PR is to work on a Hex Sticker for the website and working group.
Compared to the previous version:
* I added a light grey background (was white before)
* Moved the text inside the logo
 
Happy to hear your thoughts on this!

Preview of current style:

sticker

### CODE REVIEW

**Review by danielinteractive — COMMENTED** [review]
@ellessenne thanks for the PR, great! I would suggest to put a border around the hexagon, otherwise it is not visible on white background.

**Comment by ellessenne** [comment]
The background is already light grey ([#f8f9fa](https://www.htmlcsscolor.com/hex/F8F9FA)) so it should be visible, but I see your point. What about this updated version:

sticker

I tried a blue border (same blue as the sticker icon, which is the _default Bootstrap blue_ also used by the website) as well but it didn't look great to me.

**Comment by danielinteractive** [comment]
> The background is already light grey ([#f8f9fa](https://www.htmlcsscolor.com/hex/F8F9FA)) so it should be visible, but I see your point. What about this updated version:

looks good! I like it

**Comment by ellessenne** [comment]
Nice, thanks! Should we run it by other WG members before settling for this one?

**Comment by danielinteractive** [comment]
@ywang-gilead do you like the hex as well? 
I would propose to merge it then already... we could always change if we come up with an even better one :D

**Comment by ellessenne** [comment]
Ok, if @ywang-gilead agrees than we can merge it
I will also adjust the homepage to remove the placeholder text (before merging), or would you prefer a separate PR for that?

**Comment by danielinteractive** [comment]
@ellessenne yes exactly, please integrate as part of this PR into the homepage

**Comment by ellessenne** [comment]
Thanks @danielinteractive, that is now integrated in this PR!
I also added the sticker to the navbar (as a small logo to the left) and as a favicon.

**Comment by BrianLang** [comment]
I think it's a super nice hex. very cool.

**Comment by ywang-gilead** [comment]
I like the hex and it looks great to me! Thanks a lot to @ellessenne!

**Review by danielinteractive — APPROVED** [review]

**Comment by danielinteractive** [comment]
@ellessenne you can merge! congrats

**Pull request merged**
